name: CI-CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Validate commit messages
        run: |
          git log --grep='^(feat|fix|chore|docs|style|refactor|test|perf)\(.*\):\s.*$'



      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v2

      - name: Install dependencies in frontend and backend
        run: npm run baixar

      # - name: Install dependencies in frontend
      #   uses: bahmutov/npm-install@v1
      #   with:
      #     working-directory: frontend

      - name: Build project frontend
        run: npm run build
        working-directory: frontend

      - name: Build project backend
        run: npm run test
        working-directory: backend
