name: CI-CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Validate commit messages
        run: |
          git log --format=%s origin/..HEAD | grep -vE '^(feat|fix|chore|docs|style|refactor|test|perf)(\(.+\))?: .*' && exit 1 || exit 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend

      - name: Build project
        run: npm run build
        working-directory: frontend
